[[redirects]]
  from = "/tailwindcss/*"
  to = "/tailwindcss/index.html"
  status = 200

[[redirects]]
  from = "/bootstrap/*"
  to = "/bootstrap/index.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
